// npm run content:pool-ids [-- handle handle …] — one-off, PAID: resolves pool handles to numeric X ids
// (~$0.010 per user returned) and rewrites src/content/pool-ids.ts, so the feed never pays for a user
// lookup at run time (spec 002 T003). Run again only when the owner changes the pool.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createXClient } from '../x/client.js';
import { loadConfig } from '../config.js';
import { POOL, PLATFORM_HANDLE } from '../content/pool.js';
import { POOL_IDS } from '../content/pool-ids.js';
import { X_USER_READ_USD } from '../x/prices.js';
import { printJson, runCli } from './run.js';

const GENERATED_FILE = fileURLToPath(new URL('../content/pool-ids.ts', import.meta.url));
const HEADER = `// Generated by \`npm run content:pool-ids\` (spec 002 T003): pool handle → numeric X id. The timeline
// endpoint takes ids, not handles, and ids never change — so this is looked up once (paid, ~$0.16) and
// never at run time. Re-run only when the owner changes the pool; an account missing here is skipped.
export const POOL_IDS: Readonly<Record<string, string>> = {`;

await runCli('pool-ids', async () => {
  const asked = process.argv.slice(2).filter(Boolean);
  // The platform account is configured by id, so it is never looked up by handle.
  const handles = asked.length > 0 ? asked : POOL.map((e) => e.handle).filter((h) => h !== PLATFORM_HANDLE);
  const x = createXClient(loadConfig().X_BEARER_TOKEN);

  const ids: Record<string, string> = { ...POOL_IDS };
  let failed = 0;
  for (const handle of handles) {
    try {
      const user = await x.getUserByUsername(handle);
      ids[handle] = user.id;
      printJson({ handle: user.username, id: user.id });
    } catch (error) {
      failed += 1;
      printJson({ handle, error: error instanceof Error ? error.message : String(error) });
    }
  }

  const body = Object.entries(ids).map(([handle, id]) => `  ${JSON.stringify(handle)}: '${id}',`).join('\n');
  writeFileSync(GENERATED_FILE, `${HEADER}\n${body}\n};\n`);
  printJson({ written: GENERATED_FILE, ids: Object.keys(ids).length, failed, usd: (handles.length * X_USER_READ_USD).toFixed(2) });
});
