// Generated by `npm run content:pool-ids` (spec 002 T003): pool handle → numeric X id. The timeline
// endpoint takes ids, not handles, and ids never change — so this is looked up once (paid, ~$0.16) and
// never at run time. Re-run only when the owner changes the pool; an account missing here is skipped.
export const POOL_IDS: Readonly<Record<string, string>> = {};
