// Generated by `npm run content:pool-ids` (spec 002 T003): pool handle → numeric X id. The timeline
// endpoint takes ids, not handles, and ids never change — so this is looked up once (paid, ~$0.16) and
// never at run time. Re-run only when the owner changes the pool; an account missing here is skipped.
export const POOL_IDS: Readonly<Record<string, string>> = {
  'FabrizioRomano': '330262748',
  'AdamSchefter': '51263592',
  'NateSilver538': '16017475',
  '100trillionUSD': '918804624303382528',
  'RaoulGMI': '2453385626',
  'StatMuse': '2772543750',
  'OptaJoe': '44606764',
  'ESPNStatsInfo': '2301831317',
  'OptaAnalyst': '179500584',
  'OurWorldInData': '3169963433',
  'gelliottmorris': '57029492',
  'metaculus': '4117238354',
  'Statsbomb': '1520262590',
  'ManifoldMarkets': '1466559813752606725',
  '_1woonomic': '2286905538',
  'Kalshi': '1071484733543079936',
};
